### ISSUE TITLE
压缩完的视频快进了？

### ISSUE THREAD

**Issue by azaria810** [hpuhsp/AlbumPicker#2]

**Comment by azaria810** [comment]
![image](https://user-images.githubusercontent.com/31981580/144379770-95808c8e-a80a-49f4-b696-3a7760974d3f.png)
你这给写死速率了 ？

**Comment by hpuhsp** [comment]
确实存在不完善之处，但原则上提供可参考的解决方案，你可以根据自己项目需求适当改写。
